#include "../../../c/FlatCombining/original/flatcombining.h"
#include "../../../c/CCsynch/ccsynch.h"
#include "../../../c/u-scl/fairlock.h"
#include "../../../c/shfllock/aqs.h"
#include "../../../c/cfl/cfl.h"