// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 3,
  align: (left, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [component], [code], [tests],
  ),
  table.hline(stroke: 0.5pt),
  [executor], [681], [0],
  [lock trait + `dispatch`], [321], [0],
  [`ces`], [187], [0],
  [`fc` (delegation core)], [379], [428],
  [`UsageQueue` + `fcpq` policy], [329], [298],
  [`dispatch-pq`], [362], [428],
  [`actor`, `actor-inline`, `cfl` (references)], [953], [898],
  [`co-fifo`, `co-pq`], [694], [498],
  [stats, workload, `coro-bench`], [1647], [27],
  [tokio baseline (`tokio-bench`)], [788], [0],
  table.hline(stroke: 0.5pt),
  [total], [6341], [2577],
  table.hline(stroke: 0.8pt),
)
