// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 14,
  align: (left, right, right, right, right, right, right, right, right, right, right, right, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [], table.cell(colspan: 4, align: center)[sustained, spin], table.cell(colspan: 3, align: center)[sustained, yield], table.cell(colspan: 3, align: center)[bursty, spin], table.cell(colspan: 3, align: center)[bursty, yield],
    table.hline(start: 1, end: 5, stroke: 0.4pt),
    table.hline(start: 5, end: 8, stroke: 0.4pt),
    table.hline(start: 8, end: 11, stroke: 0.4pt),
    table.hline(start: 11, end: 14, stroke: 0.4pt),
    [lock], [Mops/s], [$o$], [$J$], [L:H], [Mops/s], [$o$], [$J$], [Mops/s], [$o$], [$J$], [Mops/s], [$o$], [$J$],
  ),
  table.hline(stroke: 0.5pt),
  [`co-pq`], [0.260], [5771], [1.000], [5.25], [0.265], [5624], [0.999], [0.120], [15566], [0.999], [0.152], [11690], [0.999],
  [`dispatch-pq-home-c256`], [0.306], [4567], [1.000], [5.44], [0.304], [4601], [1.000], [0.137], [13409], [1.000], [0.172], [10040], [1.000],
  [`fcpq-h16-home-c16`], [0.592], [1183], [0.997], [5.32], [0.590], [1194], [0.997], [0.356], [1586], [0.702], [0.351], [1613], [0.696],
  table.hline(stroke: 0.5pt),
  [`dispatch`], [0.211], [5453], [0.668], [1.00], [0.216], [5221], [0.669], [0.069], [26590], [0.678], [0.104], [16151], [0.676],
  [`tokio-mutex`], [0.233], [4419], [0.671], [1.00], [0.347], [1340], [0.671], [0.072], [25425], [0.677], [0.324], [1842], [0.671],
  [`co-fifo`], [0.352], [1200], [0.674], [1.00], [0.351], [1221], [0.674], [0.305], [2274], [0.692], [0.299], [2446], [0.694],
  [`ces-k64-home`], [0.360], [1141], [0.668], [1.00], [0.362], [1109], [0.669], [0.308], [2357], [0.686], [0.292], [2734], [0.686],
  [`fc-remote`], [0.371], [991], [0.665], [1.00], [0.371], [1003], [0.665], [0.297], [2448], [0.666], [0.287], [2715], [0.668],
  table.hline(stroke: 0.8pt),
)
