// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 9,
  align: (left, right, right, right, right, right, right, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [], table.cell(colspan: 2, align: center)[W8 sus.], table.cell(colspan: 2, align: center)[W8 bur.], table.cell(colspan: 2, align: center)[W16 sus.], table.cell(colspan: 2, align: center)[W16 bur.],
    table.hline(start: 1, end: 3, stroke: 0.4pt),
    table.hline(start: 3, end: 5, stroke: 0.4pt),
    table.hline(start: 5, end: 7, stroke: 0.4pt),
    table.hline(start: 7, end: 9, stroke: 0.4pt),
    [variant], [Mops/s], [×tm], [Mops/s], [×tm], [Mops/s], [×tm], [Mops/s], [×tm],
  ),
  table.hline(stroke: 0.5pt),
  [`tokio-mutex`], [0.241#rng[0.241][0.242]], [1.00], [0.073], [1.00], [0.232#rng[0.231][0.233]], [1.00], [0.072], [1.00],
  [`tokio-mutex-unconstrained`], [0.239], [0.99], [0.073], [1.00], [0.231#rng[0.230][0.231]], [0.99], [0.072], [1.00],
  [`async-lock`], [0.177#rng[0.177][0.239]], [0.73], [0.054], [0.75], [0.176], [0.76], [0.054], [0.75],
  [`std-mutex`], [0.204#rng[0.203][0.230]], [0.85], [0.366#rng[0.365][0.384]], [5.02], [0.167#rng[0.166][0.167]], [0.72], [0.195#rng[0.172][0.228]], [2.70],
  [`parking-lot`], [0.140#rng[0.138][0.142]], [0.58], [0.357#rng[0.356][0.359]], [4.90], [0.108#rng[0.108][0.114]], [0.46], [0.125#rng[0.122][0.154]], [1.73],
  table.hline(stroke: 0.5pt),
  [`dispatch`], [0.218#rng[0.217][0.218]], [0.90], [0.071], [0.97], [0.214#rng[0.214][0.215]], [0.92], [0.071], [0.98],
  [`dispatch-home`], [0.253], [1.05], [0.147#rng[0.146][0.150]], [2.01], [0.239#rng[0.239][0.241]], [1.03], [0.172#rng[0.161][0.172]], [2.39],
  [`ces-k64-home`], [0.381#rng[0.380][0.381]], [1.58], [0.317#rng[0.314][0.318]], [4.36], [0.372], [1.60], [0.350#rng[0.349][0.350]], [4.85],
  [`fc-remote`], [0.387#rng[0.387][0.388]], [1.61], [0.307#rng[0.307][0.308]], [4.22], [0.378#rng[0.378][0.379]], [1.63], [0.358#rng[0.357][0.358]], [4.97],
  [`fcpq-h16-home`], [0.571#rng[0.569][0.571]], [2.37], [0.365#rng[0.365][0.366]], [5.01], [0.547#rng[0.545][0.549]], [2.36], [0.392], [5.44],
  table.hline(stroke: 0.8pt),
)
