// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 6,
  align: (left, left, right, right, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [lock], [clamp], [win.], [svc. $J$], [L:H], [max. wait],
  ),
  table.hline(stroke: 0.5pt),
  [`fcpq-h16-home`], [8 passes], [09-29], [0.940], [3.64], [10],
  [`fcpq-h16-home`], [16 passes], [09-29], [0.997], [5.51], [17],
  [`fcpq-h16-home`], [off], [09-29], [0.997], [5.48], [106],
  table.hline(stroke: 0.5pt),
  [`dispatch-pq-home`], [16 hand-offs], [09-29], [0.672], [1.00], [--],
  [`dispatch-pq-home`], [256 hand-offs], [09-29], [1.000], [5.63], [--],
  [`dispatch-pq`], [off], [09-29], [1.000], [5.83], [--],
  table.hline(stroke: 0.5pt),
  [`co-pq`], [256 hand-offs], [09-30], [1.000], [5.25], [257],
  [`co-pq`], [off], [09-30], [1.000], [5.27], [3102],
  table.hline(stroke: 0.8pt),
)
