// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 7,
  align: (left, right, right, right, right, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [lock], [$"CS"_L$], [$"CS"_H$], [L:H ops], [model $J$], [measured $J$], [L:H for $J=1$],
  ),
  table.hline(stroke: 0.5pt),
  [`dispatch`], [1391], [8403], [1.00], [0.661], [0.661#rng[0.661][0.664]], [6.04],
  [`ces`], [1280], [8295], [1.00], [0.651], [0.651#rng[0.650][0.652]], [6.48],
  [`fc`], [1354], [8355], [1.00], [0.658], [0.658], [6.17],
  [`tokio-mutex`], [1404], [8402], [1.00], [0.663], [0.663#rng[0.662][0.663]], [5.98],
  table.hline(stroke: 0.8pt),
)
