// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 7,
  align: (left, left, right, right, right, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [cell], [clamp], [Mops/s], [svc. $J$], [L:H], [heavy p99 (µs)], [burden $J$],
  ),
  table.hline(stroke: 0.5pt),
  [W8 sus. b31], [8], [0.540#rng[0.539][0.540]], [0.940#rng[0.939][0.940]], [3.64], [357.4], [1.000],
  [W8 sus. b31], [16], [0.612#rng[0.611][0.614]], [0.997], [5.51], [625.5], [1.000],
  table.hline(stroke: 0.5pt),
  [W8 sus. b0], [8], [0.540#rng[0.540][0.543]], [0.930#rng[0.929][0.931]], [3.50], [268.1], [0.501],
  [W8 sus. b0], [16], [0.614#rng[0.613][0.617]], [0.997], [5.53], [655.3], [0.970],
  table.hline(stroke: 0.5pt),
  [W16 sus. b31], [8], [0.531#rng[0.530][0.531]], [0.937#rng[0.937][0.938]], [3.57], [342.5], [0.999],
  [W16 sus. b31], [16], [0.604#rng[0.603][0.604]], [0.997], [5.45], [565.9], [0.998],
  table.hline(stroke: 0.5pt),
  [W8 bur. b31], [8], [0.358#rng[0.357][0.358]], [0.697#rng[0.696][0.697]], [1.23], [78.2], [1.000],
  [W8 bur. b31], [16], [0.358#rng[0.357][0.358]], [0.697#rng[0.696][0.697]], [1.23], [78.2], [1.000],
  table.hline(stroke: 0.5pt),
  [W16 bur. b31], [8], [0.386], [0.734#rng[0.734][0.735]], [1.48], [70.7], [0.998],
  [W16 bur. b31], [16], [0.386], [0.734#rng[0.734][0.735]], [1.48], [70.7], [0.998],
  table.hline(stroke: 0.8pt),
)
