// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 3,
  align: (left, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [component], [code], [tests],
  ),
  table.hline(stroke: 0.5pt),
  [executor], [681], [0],
  [lock trait + `dispatch`], [305], [0],
  [`ces`], [180], [0],
  [`fc` (delegation core)], [379], [428],
  [`fcpq` policy], [281], [298],
  [`actor`, `actor-inline`], [479], [224],
  [stats, workload, `coro-bench`], [1119], [27],
  [tokio baseline (`tokio-bench`)], [765], [0],
  table.hline(stroke: 0.5pt),
  [total], [4189], [977],
  table.hline(stroke: 0.8pt),
)
