// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 8,
  align: (left, right, right, right, right, right, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [], table.cell(colspan: 2, align: center)[`tokio-mutex`], table.cell(colspan: 2, align: center)[`async-lock`], table.cell(colspan: 3, align: center)[coro / `tokio-mutex` LIFO off],
    table.hline(start: 1, end: 3, stroke: 0.4pt),
    table.hline(start: 3, end: 5, stroke: 0.4pt),
    table.hline(start: 5, end: 8, stroke: 0.4pt),
    [cell], [LIFO on], [off], [on], [off], [`ces-k64-home`], [`fc-remote`], [`fcpq-h16-home`],
  ),
  table.hline(stroke: 0.5pt),
  [W8 sus.], [0.231#rng[0.230][0.242]], [0.250#rng[0.243][0.251]], [0.176#rng[0.176][0.403]], [0.237#rng[0.233][0.241]], [1.52], [1.55], [2.28],
  [W8 bur.], [0.072#rng[0.072][0.073]], [0.263#rng[0.261][0.265]], [0.072#rng[0.054][0.072]], [0.250#rng[0.249][0.253]], [1.21], [1.17], [1.39],
  [W16 sus.], [0.229#rng[0.229][0.232]], [0.248#rng[0.245][0.253]], [0.176], [0.234#rng[0.232][0.244]], [1.50], [1.53], [2.21],
  [W16 bur.], [0.072], [0.248#rng[0.246][0.251]], [0.054#rng[0.054][0.072]], [0.237#rng[0.235][0.244]], [1.41], [1.44], [1.58],
  table.hline(stroke: 0.8pt),
)
