// generated by scripts/make_tables.py -- do not edit
#import "../lib.typ": rng
#table(
  columns: 9,
  align: (left, right, right, right, right, right, right, right, right),
  stroke: none,
  table.hline(stroke: 0.8pt),
  table.header(
    [], table.cell(colspan: 2, align: center)[W8 sus.], table.cell(colspan: 2, align: center)[W8 bur.], table.cell(colspan: 2, align: center)[W16 sus.], table.cell(colspan: 2, align: center)[W16 bur.],
    table.hline(start: 1, end: 3, stroke: 0.4pt),
    table.hline(start: 3, end: 5, stroke: 0.4pt),
    table.hline(start: 5, end: 7, stroke: 0.4pt),
    table.hline(start: 7, end: 9, stroke: 0.4pt),
    [variant], [svc. $J$], [st. c/b], [svc. $J$], [st. c/b], [svc. $J$], [st. c/b], [svc. $J$], [st. c/b],
  ),
  table.hline(stroke: 0.5pt),
  [`tokio-mutex`], [0.663#rng[0.662][0.663]], [0/0], [0.668#rng[0.668][0.669]], [0/0], [0.666#rng[0.665][0.668]], [0/0], [0.672#rng[0.671][0.674]], [0/0],
  [`tokio-mutex-unconstrained`], [0.665#rng[0.664][0.665]], [0/0], [0.669#rng[0.669][0.670]], [0/0], [0.667], [0/0], [0.672], [0/0],
  [`async-lock`], [0.016#rng[0.016][0.661]], [63#rng[0][63]/0#rng[0][2]], [0.062], [15/0#rng[0][1]], [0.016], [63/0], [0.062], [15/0],
  [`std-mutex`], [0.055#rng[0.047][0.057]], [56/8], [0.255#rng[0.253][0.256]], [8/8], [0.234], [48/16], [0.782#rng[0.767][0.807]], [0/16],
  [`parking-lot`], [0.048#rng[0.048][0.049]], [56/8], [0.250], [8/8], [0.197#rng[0.181][0.198]], [48/16], [0.774#rng[0.692][0.775]], [0/16],
  table.hline(stroke: 0.5pt),
  [`dispatch`], [0.659], [0/0], [0.674], [0/0], [0.663], [0/0], [0.679], [0/0],
  [`dispatch-home`], [0.669], [0/0], [0.669#rng[0.669][0.670]], [0/0], [0.674#rng[0.673][0.674]], [0/0], [0.673#rng[0.672][0.673]], [0/0],
  [`ces-k64-home`], [0.659], [0/0], [0.678#rng[0.677][0.679]], [0/0], [0.661#rng[0.661][0.662]], [0/0], [0.663], [0/0],
  [`fc-remote`], [0.653], [0/0], [0.655#rng[0.655][0.656]], [0/0], [0.659#rng[0.659][0.660]], [0/0], [0.662], [0/0],
  [`fcpq-h16-home`], [0.930], [0/0], [0.685#rng[0.685][0.686]], [0/0], [0.933#rng[0.932][0.934]], [0/0], [0.726#rng[0.724][0.727]], [0/0],
  table.hline(stroke: 0.8pt),
)
