= Introduction <sec:intro>

Locks are among the oldest and most widely deployed synchronization primitives. Embedded key-value stores, database engines, file systems, and the operating system itself rely on them to protect the state that every request must eventually touch @redb @upscaledb. Under steady load a contended lock is never idle: at every hand-off it decides whose code runs next on the shared state. A contended lock is therefore also a _scheduler_ of critical-section time, and like any scheduler it can be fair or unfair.

Patel et al. showed that the classic notion of lock fairness is the wrong one @patel2020scl. A ticket lock or MCS @mellorcrummey1991mcs grants the lock in FIFO order, so each thread acquires it equally often. But when critical sections differ in length, a thread that holds the lock longer on every turn receives more of the machine, and the lock rather than the CPU scheduler decides each thread's share. They called this _scheduler subversion_ and proposed _lock usage fairness_ as the correct goal. The effect is easy to reproduce in a production system. When 1-record and 64-record writers share redb's single-writer lock, MCS achieves a Jain fairness index @jain1984fairness of only 0.85--0.86 over time spent in the critical section. The problem, then, is well understood. This paper is about what it _costs_ to solve it.

Fairness is expensive for a structural reason. In a conventional lock, the thread that wins the lock also executes the critical section. Choosing _who is served next_ therefore also chooses _which core touches the protected data next_. A lock that wants to control the first has, in effect, three options for the second, and each has a cost.

First, it can hand the lock to whichever thread the policy picks and let the data follow. FIFO locks do this, and so pay a cache migration on nearly every hand-off. In redb, MCS incurs 93--126 cross-core cache transfers per transaction and commits 11--19% fewer transactions per second than the native mutex. Second, it can bias the choice toward the thread that is already local, as the native mutex does by letting the releasing thread barge back in, or as NUMA-aware locks such as CNA @dice2019cna and ShflLock @kashyap2019shfllock do across sockets. This preserves locality by giving up precisely the freedom a fair policy needs; redb's native mutex is as fast as any lock we measured and also the least fair. Third, it can keep the data on one thread for a while by reserving the lock for it. u-SCL does this with _lock slices_ @patel2020scl. Its fairness target, _lock opportunity_,
$ "LOT"(i) = sum "CS"(i) + sum "Lock Idle Time", $
credits idle time as opportunity, so a slice owner that leaves the critical section to run its own code keeps the lock reserved while others wait. u-SCL buys fairness and locality with _work conservation_, and its waiters sleep, which ties its speed to the operating system's wake-up latency and power management.

The common root of these costs is that the lock's scheduling decision and its execution site are the same decision. _Delegation_ separates them. In flat combining @hendler2010fc, CC-Synch @fatourou2012ccsynch, RCL @lozi2012rcl, and ffwd @roghanchi2017ffwd, threads publish their critical sections as requests, and a single _combiner_ executes all pending requests on their behalf. The data stays in the combiner's cache no matter whose request runs, and the combiner never idles while work is pending. Existing delegation locks have used this separation only for speed: they serve requests in arrival or scan order, and so remain as usage-unfair as FIFO locks. In redb, flat combining reaches a usage fairness of only 0.83--0.85.

We observe that the same separation makes fairness cheap. Once execution no longer moves with the lock, the order in which requests are served stops being a question of where the data goes and becomes a pure scheduling decision, made by one thread, at the point where the next critical section is chosen. The combiner already sees every pending request, and because it executes each one itself, it can measure each one's cost for the price of two timestamp reads. Changing _who_ is served next then costs a request hand-off, independent of the size of the protected data.

We build on this observation with FC-PQ, a _service-fair delegation_ lock. FC-PQ charges each request's critical-section time to the thread that submitted it and has the combiner serve pending requests in order of lowest accumulated service, in the spirit of virtual-time fair queueing @demers1989wfq. A fast path lets an uncontended thread execute directly, so fairness costs nothing when there is no one to be fair to. FC-PQ pursues SCL's goal, a fair share of critical-section time, but in work-conserving form: shares are measured over the time the lock actually spends serving each thread, with no credit for idle time, and whenever any request is pending, the combiner runs one.

We evaluate FC-PQ inside two real databases: redb, where it replaces the single-writer admission so each critical section is a whole write transaction, and UpScaleDB, where it replaces the environment mutex that serializes finds and inserts. We measure fairness over critical-section time charged to the requesting thread, and we fix the CPU clock. Without the latter, u-SCL's sleeping waiters ran at about 1 GHz while spinning locks ran at turbo frequency, which made FC-PQ appear two to three times faster than u-SCL; at a fixed 3.0 GHz that apparent advantage disappears.

The results support the cost argument. In redb, with the clock fixed, FC-PQ reaches a usage fairness of 0.94--0.995, close to u-SCL's 1.00 and well above MCS and flat combining, while running at the speed of the unfair native mutex: with four to eight writers, FC-PQ, flat combining, u-SCL, and the native mutex all commit 29.7--32.3k transactions per second, whereas MCS commits 26.2--26.4k. FC-PQ incurs 10--18 cross-core transfers per transaction against MCS's 93--126. In other words, delegation removes the migration cost that FIFO fairness pays, without the locality bias that the native mutex relies on.

Delegation does not make fairness free, and we report where the cost remains. Redistributing service is itself a cost: because FC-PQ serves short writers more often, it commits 0.72--0.96$times$ the records per second of MCS. Its waiters spin, so it spends about four times the CPU time of u-SCL at equal throughput and assumes no more threads than cores. And on redb, u-SCL matches FC-PQ's throughput, because redb's writers submit back to back, the one case in which reserving the lock never wastes it. We therefore state, as a falsifiable prediction, that FC-PQ's advantage over slice-based locks grows as $min(N, (c + n) / c)$ for $N$ threads with critical-section time $c$ and non-critical time $n$, and that its advantage over caller-executed fair locks grows with the size of the protected working set.

This paper makes the following contributions:

- We argue that the cost of lock usage fairness is structural: in caller-executed locks the scheduling decision also moves the protected data, forcing a choice among migration, locality bias, and idling.
- We show that delegation removes this coupling, and we design FC-PQ, a work-conserving, usage-fair delegation lock with a fast path proven sound for the uncontended case.
- We develop a methodology for measuring usage fairness in real systems: service charged to the requester, correctness gates inside the database, and control of the CPU clock. Without clock control, comparisons between spinning and sleeping locks can be dominated by power management rather than lock design.
- We evaluate FC-PQ in redb and UpScaleDB against the native mutex, MCS, flat combining, and u-SCL, and report which costs of fairness delegation removes and which remain.

The rest of this paper is organized as follows. Section 2 reviews scheduler subversion and lock usage fairness and analyzes the cost of fairness in caller-executed locks. Section 3 presents the design and implementation of FC-PQ. Section 4 describes our methodology, and Sections 5 and 6 evaluate FC-PQ in redb and UpScaleDB. We discuss limitations in Section 7 and related work in Section 8, and conclude in Section 9.
