= Introduction <sec:intro>

Databases, file systems, and operating systems serialize access to their most contended state through locks @redb @upscaledb. Under load, a lock is therefore also a _scheduler_: at every hand-off it decides whose critical section runs next. Patel et al. showed that the usual notion of lock fairness, granting the lock in the order threads asked for it, is the wrong goal: when critical sections differ in length, a thread that holds the lock longer on every turn receives more of the machine @patel2020scl. They called this _scheduler subversion_ and proposed _lock usage fairness_, which divides the time spent holding the lock rather than the number of turns. The effect is easy to reproduce. The MCS lock @mellorcrummey1991mcs, a standard queue lock that hands the lock to waiters strictly in arrival order, gives each of redb's 1-record and 64-record writers the same number of turns, yet the 64-record writers hold the lock about 70% of the time. Jain's fairness index @jain1984fairness, which is 1 when every thread gets the same time in the critical section, is only 0.85--0.86.

Usage-fair locks solve this problem. u-SCL measures how long each thread holds the lock and grants the lock in _slices_: for a few milliseconds one thread owns the lock and may reacquire it freely, then ownership passes to the next waiter, and a thread that has used more than its share is made to sleep before it may queue again @patel2020scl. CFL borrows its policy from CFS, the Linux CPU scheduler, which always runs the thread that has received the least CPU time so far. CFL likewise tracks how long each thread has held the lock, weighted by its priority, and reorders the wait queue so that the thread with the least accumulated hold time goes next; by default it never leaves the lock idle while a thread waits @park2024cfl. Both work. In redb, u-SCL raises the Jain index to 1.000, and CFL protects a latency-critical service from a co-located batch job that contends for the same kernel lock @park2024cfl.

Both locks, however, keep a property shared by every lock: the thread that is served runs its own critical section. The protected data therefore lives in the cache of whichever core ran the last holder, and a fair hand-off to a thread on another core forces the data to follow. In redb, each transaction under MCS fetches 93--126 cache lines directly from another core's cache. NUMA-aware queue locks such as CNA @dice2019cna and ShflLock @kashyap2019shfllock reorder the wait queue so that the lock passes between threads on the same socket for a while, which makes each transfer cheaper, but the data still moves on every hand-off @gupta2023tclocks. Chiplet processors, which split a socket into dies with separate last-level caches @naffziger2021chiplet, make each move costlier even within a socket. A lock can avoid moving the data only by letting the same thread, or threads on the same socket, keep the lock, which relaxes fairness, and usage-fair locks do exactly this: u-SCL's slices let one thread keep the lock for milliseconds, and CFL prefers waiters on the current socket and lets a socket keep the lock for a short grace period at the expense of short-term fairness @park2024cfl. General-purpose locks make the same trade by default. The `Mutex` of Rust's widely used `parking_lot` library lets a releasing thread take the lock straight back and forces a hand-off to the longest waiter only about every 0.5 ms, while its strictly first-come-first-served `FairMutex` is documented as "generally slower, but sometimes needed" @parkinglot.

A second cost has nothing to do with where the data lives. A lock can choose only among the threads that are waiting when it hands off, yet a thread can be owed service without waiting: it may still be waking up after sleeping in the kernel, or the CPU scheduler may have just taken its core away. The two usage-fair locks answer this differently. u-SCL keeps the lock reserved for its slice owner while that thread is away, so the lock can sit idle while others wait; CFL's authors criticize this as not _work-conserving_. CFL instead gives the turn to whoever is waiting, and even lets a newly arriving thread take the lock ahead of a sleeping waiter to hide the waiter's wake-up delay, which its authors note can significantly degrade fairness @park2024cfl. Neither choice is a mistake. Each pays for the absent thread, in idle lock time or in lost share. The remaining option, having waiters spin on the CPU instead of sleeping so that none is ever absent, pays in CPU time.

The first cost rests on an assumption so basic that it usually goes unstated: the thread that is served is the thread that executes. _Delegation_ locks are a special kind of lock that breaks it. In flat combining @hendler2010fc, threads do not run their critical sections themselves; each publishes its critical section as a request in a shared list, and whichever thread holds the lock, the _combiner_, runs the pending requests one after another on its own core. The data therefore stays in one cache no matter whose request runs. Successors of flat combining, up to TCLocks @gupta2023tclocks, which applies delegation to unmodified lock-based code, use this separation for speed and transparency but serve requests in the order they were published, and so remain as usage-unfair as first-come-first-served locks. Once execution no longer follows the lock, however, choosing _whose_ request runs next becomes a pure scheduling decision, and the combiner, which executes every request, can measure each one's cost for the price of two timestamp reads. The second cost remains: a combiner, too, can serve only the requests that have been published.

We build on this observation with FC-PQ, a usage-fair delegation lock. Its combiner serves pending requests in order of least accumulated critical-section time, in the spirit of virtual-time fair queueing @demers1989wfq, and a fast path lets an uncontended thread execute directly. FC-PQ pursues SCL's goal in work-conserving form: whenever a request is pending, the combiner runs one. To reason about when this pays, we develop an analysis framework that splits the price of fairness into accounting, migration, idleness, and redistribution, and shows that delegation leaves mainly the first and last.

We evaluate FC-PQ inside redb and UpScaleDB, charging service to the requesting thread, with the CPU clock fixed. On redb, FC-PQ matches u-SCL's fairness (0.94--0.995) at the native mutex's throughput, with 10--18 cross-core transfers per transaction where MCS incurs 93--126. Our prototype's waiters spin, which costs CPU time and limits it to no more threads than cores; this is an implementation choice, not a property of usage-fair delegation, since waiting and serving are independent and delegation locks can park their waiters @gupta2023tclocks. On redb's back-to-back writers FC-PQ only ties u-SCL, whose slices waste nothing when threads never leave the lock. We expect FC-PQ to pull ahead when threads do real work between critical sections and when the protected data is large; Section 8 states these predictions.

This paper makes the following contributions:

- We show that the cost of lock usage fairness comes from coupling who is served with where the critical section runs, which forces a fair lock to pay in migration or, if it reserves the lock, in idleness.
- We give an analysis framework that decomposes the price of fairness and predicts when delegation lowers it.
- We design FC-PQ, a work-conserving, usage-fair delegation lock with a fast path proven sound for the uncontended case.
- We evaluate FC-PQ in redb and UpScaleDB with service charged to the requester and a fixed CPU clock, and report which costs of fairness delegation removes and which remain.

Section 2 reviews lock usage fairness; Section 3 develops the analysis framework; Section 4 presents FC-PQ; Section 5 describes our methodology; Sections 6 and 7 evaluate redb and UpScaleDB; Section 8 discusses limitations and predictions; Section 9 covers related work.
